config/routes.rb
Rails.application.routes.draw do
  # devise_for :users

  devise_for :users, controllers: { registrations: "registrations", passwords: "passwords"}

  resource :user, only: [:edit] do
    collection do
      patch 'update_password'
    end
  end
  resources :projects do
    resources :photos, only: [:create, :destroy]
  end

  get 'admin',to: 'admin#index'

  get 'pages/index'

  get 'pages/about'

  get 'pages/projects'

  get 'pages/numbers'

  get 'pages/contact'

  root 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :project
end

app/models/project.rb
class Project < ApplicationRecord
  mount_uploader :logo, ImageUploader
  has_many :photos
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout 'adminlayout'
  before_action :authenticate_user!
  def index
    @projects = Project.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :set_widget
  def index
  	@projects = Project.last(2)
  end

  def about
  end

  def projects
  	@projects = Project.all
  end

  def numbers
  end

  def contact
    @projects = Project.all
  end

  private
    def set_widget
      @widget = Project.all
    end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!


  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)
    @project = Project.find(params[:project_id])

    @photo.project = @project


    if @photo.save
      redirect_to edit_project_path(@project)
    else
      redirect_to @project, notice: 'error al crear la foto'
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy

    @photo.destroy
    @project = Project.find(params[:project_id])

    redirect_to edit_project_path(@project)

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:image, :project_id)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  layout 'adminlayout'
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: :show
  before_action :set_widget
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @projects = Project.all
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to edit_project_path(@project)
    else
      redirect_to edit_project_path(@project), notice: 'error'
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    if @project.update(project_params)
      redirect_to edit_project_path(@project)
    else
      redirect_to edit_project_path(@project), notice: 'error'
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    redirect_to admin_path
  end

  def make_sold_out
    @project = Project.find(params[:id])
    if @project.sold_out
      @project.sold_out = false
    else
      @project.sold_out = true
    end
    if @project.save
      redirect_to edit_project_path(@project)
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end


    def set_widget
      @widget = Project.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description, :logo)
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  def destroy
    super
    redirect_to root_path
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

def edit
  @user = current_user
end

def update_password
  @user = current_user
  if @user.update(user_params)
    # Sign in the user by passing validation in case their password changed
    bypass_sign_in(@user)
    redirect_to admin_path
  else
    render "edit"
  end
end

private

def user_params
  # NOTE: Using `strong_parameters` gem
  params.require(:user).permit(:password, :password_confirmation)
end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<div class="container-fluid skin">
  <table class="table table-hover">
    <thead>
      <tr>
        <th>Name</th>
        <th>Nº Photos</th>
        <th>Actions</th>
      </tr>
    </thead>
    <% @projects.each do |project| %>
      <tr>
        <td><%= link_to project.name, project_path(project) %></td>
        <td><%= project.photos.count %></td>
        <td><%= link_to 'Edit', edit_project_path(project), class: 'btn btn-primary btn-sm' %></td>
        <td><%= link_to 'Delete', project_path(project), method: :delete, class: 'btn btn-danger btn-sm' %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/layouts/adminlayout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TownhouseIg</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script
    src="https://code.jquery.com/jquery-2.2.4.min.js"
    integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44="
    crossorigin="anonymous"></script>
   <link href="https://fonts.googleapis.com/css?family=Abel|Oswald" rel="stylesheet">
    <script  src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user.present? %>
      <%= render 'shared/navbaradmin' %>
    <% end %>

    <%= yield %>




    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.min.js"></script>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TownhouseIg</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Abel|Oswald" rel="stylesheet">
    <script  src="https://use.fontawesome.com/releases/v5.0.6/js/all.js"></script>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <div class=" skin">
      
    
    <%= yield %>

    <%= render 'shared/footer' %>

    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>

app/views/pages/about.html.erb
<%= render 'shared/navbar' %>
	<div class="container-fluid bkg-about alice d-flex justify-content-center ">
		<div class="row tint boxed-style p-5">
			<div class="col-md-12  ">

				<figure class="figure">
		          <%= image_tag 'Logowhite-01.png', class: 'figure-img img-fluid w-50' %>
				</figure>
				<h3>Build Tomorrow Today </h3>

			</div>
		</div>
	</div>
	<div class="container-fluid  underline alice about-info-box">
		<div class="row">



			<div class="col-md-12">
				<div class="">

					<p class="content">
						Townhouse IG is a family-owned real estate investment firm. We deliver a single low-risk plan that can help you lay the foundation for a brighter future. Our initial investment starts at $40,000 dollars and up. We’re a company that treats your money like our own and our customers like family. We don’t risk it on the stock market and we never invest it in a project we don’t 100% believe in. Townhouse IG also operates with 100% transparency and never resorts to asterisks or fine print. What you read is what you get: 9 to 12.5-percent returns in just 12 months on a 24 Month investment product. Our family has decades of experience in construction and real estate—and, up until now, has relied on family investors to get the job done. With 6 profitable projects under our belt, we decided to open the door to any American dreaming of a better future. But, we’re not just a family-owned construction business. We’re one headed by a chairman with more than 10 years of accounting and finance experience. So, if you’re tired of riding the Wall Street rollercoaster, consider giving us a call. Put your trust in Townhouse IG.
					</p>

				</div>
			</div>

			<div class="col-md-12 text-right mr-top">

					<%= link_to pages_projects_path do  %>
			          <button class="btn  m-1" >Projects</button>
			        <% end %>
					<button class="btn btn-info m-1">Contact Us<i class="fas fa-chevron-right"></i></button>
			</div>
		</div>
	</div>

app/views/pages/contact.html.erb
<%= render 'shared/navbar' %>
<div class="container">
	<div class="row d-flex align-items-stretch">
		<div class="">
			
		</div>

		<div class="col-md-6 d-flex flex-column p-5">
			<form>

				<div class="form-group">
				    <label for="exampleFormControlInput1">Name</label>
				    <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="">
				</div>


				<div class="form-group">
				    <label for="exampleFormControlInput1">Phone</label>
				    <input type="text" class="form-control" id="exampleFormControlInput1" placeholder="">
				</div>

			  <div class="form-group">
			    <label for="exampleFormControlInput1">Email address</label>
			    <input type="email" class="form-control" id="exampleFormControlInput1" placeholder="">
			  </div>
			  

			  
			  

			  <div class="form-group">
			    <label for="exampleFormControlTextarea1">Message</label>
			    <textarea class="form-control" id="exampleFormControlTextarea1" rows="3"></textarea>
			  </div>
			</form>
		</div>

		<div class="col-md-6 contact-div d-flex align-items-center p-5">
			<ul class="contact-info-list">
				<li>
					<h3>Address</h3>
					<h4>21044 Sherman way Ste 233, </br>
					Canoga park,CA 91303</h4>
				</li>
				<li>
					<h3>Email</h3>
					<h4>contact@townhouseig.cl</h4>
				</li>
				<li>
					<h3>Fax</h3>
					<h4>818.610.8025</h4>
					<h3>Phone</h3>
					<h4>310.601.7279</h4>
					
				</li>
			</ul>
		</div>
		

	</div>
</div>

app/views/pages/index.html.erb
<div class="container-fluid img-container">
  <div class="row">
    <div class="d-flex align-items-center justify-content-end text-right w-100 h-100">
      <div class="caption">
          <%= image_tag 'Logowhite-01.png', class: 'logo' %>
          <h5 class="p-4" style="">Build Tomorrow Today</h5>

          <%= link_to pages_projects_path do  %>
          <button class="btn btn-lg  m-3" >See Projects</button>
        <% end %>
    
      </div>

    </div>

  </div>
</div>




<%= render 'shared/navbar' %>



<main class="container-fluid " >
  <div class="row d-flex align-items-stretch">
    <div class=" col-md-6 col-lg-6 col-box-1 p-0">

    </div>
    <div class="col-md-6  p-5">
      <h1 class="title">
        TownHouse Investment Group
      </h1>
      <p class="content p-2">
        With average returns of <span>12.5</span>-percent—Townhouse IG helps lay the foundation for a bright
        future for you and your family. Invest with us and break into real estate the simple way: no asterisks and
        no fine print. So, don’t waste another day waiting for the right opportunity to come. It’s here—and its
        name is <span>Townhouse IG.</span>
      </p>
     
        <%= link_to pages_about_path do  %>
          <button class="btn btn-outline-info m-1">More about Townhouse IG<i class="fas fa-chevron-right"></i></button>
        <% end %>
        <%= link_to pages_projects_path do  %>
          <button class="btn btn-outline-info m-1" >Projects</button>
        <% end %>


    </div>
    
  </div>
</main>

<div class="container-fluid pd-100 metal-bkg home-projects fixed-bkg" ')">
  <div class="row ">
    <div class="col-md-12 text-center">

      <%= render 'shared/projectstitle' %>

    </div>
    <div class="col-md-12">
       <div class="row d-flex justify-content-center projects-row " >

          <% @projects.each do |project| %>
            <div class="card p-2 m-1" style="width: 18rem;">
                <div class="card-img-box" style="background-image:url('<%= project.photos.first.image %>')">

                </div>
               <!--<%= image_tag project.photos.first.image, class: 'card-img-top img-fluid imagen' %>-->
                <div class="card-body d-flex flex-column">

                  <div class="card-logo-box" style="background-image:url('<%= project.logo %>')" >
                    <!--<%= image_tag project.logo, class: 'figure-img img-fluid', style: 'width: 8rem;' %>-->
                  </div>
                  <h5 class="card-title title-h "><%= project.name %></h5>


                  <%= link_to 'See projects', project_path(project), data: { turbolinks: false }, class: 'btn btn-info btn-sm mt-auto' %>


                </div>
            </div>
          <% end %>

        </div>
    </div>



  </div>


   

    <div class="row">

      <div class="offset-md-4 col-md-4 mt-2">
        <%= link_to 'ALL PROJECTS', pages_projects_path, class: 'title btn btn-outline-info mt-auto d-block all-p-btn' %>
      </div>
    </div>





</div>

<!--<div class="container-fuid pt-5 pb-5 section-3">
  <div class="row">



    <div class="offset-md-3 col-md-6 text-center section3">

      <h3 class="title-h">
        LET’S TALK NUMBERS:
      </h3>
      <p class="content p-2">
        There is a principle in finance called the rule of 72. It’s a measure of how quickly your money
        doubles at a certain rate of return. <br>With us, that averages out to just six years. Here are some important
        things you should know if you’re ready to invest with us:
      </p>
      <ul>
        <li>Our minimum investment amount is 50,000 USD.</li>
        <li>Average returns range between 11 and 14 percent</li>
        <li>Fees total x per one round of investment</li>
      </ul>
    </div>

  </div>
</div>-->



<div class="container-fluid " >
  <div class="row d-flex align-items-stretch direct-row">
    <div class=" col-md-6 col-lg-6 direct-img p-0">

    </div>
    <div class="col-md-6  p-5 text-center">
      <p><i class="fas fa-map-marker"></i></p>
      <h2 class="title">
        Address
      </h2>
      
       <p>21044 Sherman way Ste 233<br>Canoga park,CA 91303<br></p>

    </div>
    
  </div>
</div>



<!--<div class="container-fluid counts align-middle">
  <div class="row paralax">
    <div class="col-md-4">
      <p class="count ">55</p>
    </div>
    <div class="col-md-4">
      <p class="count ">55</p>
    </div>
    <div class="col-md-4">
      <p class="count">55</p>
    </div>
  </div>
</div>-->

app/views/pages/numbers.html.erb
<%= render 'shared/navbar' %>
	<div class="container-fluid bkg-numbers alice d-flex justify-content-center ">
		<div class="row tint boxed-style p-5">
			<div class="col-md-12  p-5">

				<h3>Lets Talk Numbers</h3>

			</div>
		</div>
	</div>
	<div class="container-fluid  underline alice numbers-info-box">
		<div class="row">



			<div class="col-md-12">
				<div class="">

					<p class="content">
            There is a principle in finance called the rule of 72. It’s a measure of how quickly your money doubles base on your interest rate. With us, that averages out to just six years. Here are some important things you should know if you’re ready to invest with us: Our minimum investment amount is $40,000 USD. Average returns range between 9 and 12.5-percent.All of our investments our on a 24 Month period and we do not make monthly distributions.On month 24 you will receive your funds plus interest earn as a 1 lump sum for the entire amount.You then can choose to reinvest all or some of your money again on a new 24 month period investment.Example: If you invest x amount you will receive between 18-percent and 25-percent return on investment. if you invest $100.00 USD you will receive $125.000 USD on month 24.Simple and clear just like we like it.We believe that under this simple rules we can go a long way
					</p>

				</div>
				
				

			</div>

			<div class="col-md-12 mt-5">
				<div class="">
					<h2 class="slogan">The Rule of 72</h2>

					<p class="content">
            The Rule of 72 says that to find the number of years needed to double your money at a given interest rate, you just divide 72 by the interest rate. For example, if you want to know how long it will take to double your money at nine percent interest, divide 72 by 9 and get 8 years
					</p>

				</div>
				<a href="https://goodcalculators.com/rule-of-72-calculator/">
					<button class="btn  m-1" >Rule 72 Calculator Website</button>
				</a>
				<p></p>
		          
		       
				

					
			</div>
			

			<div class="col-md-12 text-right mr-top">

					
			</div>
		</div>
	</div>

app/views/pages/projects.html.erb
<%= render 'shared/navbar' %>
<div class="container mr-top fixed-bkg" style="background-image:url('/assets/bkgiso.png')">

  <div class="row">
    <div class="col-md-12 text-center home-projects">
      <%= render 'shared/projectstitle' %>
    </div>
  </div>


  <div class="row d-flex justify-content-center p-3 mt-5">

    <% @projects.each do |project| %>
      <div class="card p-2 m-1" style="width: 18rem;">
          <div class="card-img-box" style="background-image:url('<%= project.photos.first.image %>')">
            
          </div>
          <% if project.sold_out %>
            <div class="sold">
              SOLD OUT
            </div>
            
          <% end %>
         <!--<%= image_tag project.photos.first.image, class: 'card-img-top img-fluid imagen' %>-->
          <div class="card-body d-flex flex-column">
            
            <div class="card-logo-box" style="background-image:url('<%= project.logo %>')" >
              <!--<%= image_tag project.logo, class: 'figure-img img-fluid', style: 'width: 8rem;' %>-->
            </div>
            <h5 class="card-title title-h"><%= project.name %></h5>
            
          
            <%= link_to 'See project', project_path(project), data: { turbolinks: false }, class: 'btn btn-info btn-sm mt-auto' %>
          
            
          </div>
      </div>
    <% end %>

    
  </div>

</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg  bg-light ">
  <a class="navbar-brand" href="#">
    <%= image_tag 'logo-01.png' %>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="<%= root_path %>">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <%= link_to 'About Us', pages_about_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Projects', pages_projects_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Lets Talk Numbers', pages_numbers_path, class: 'nav-link' %>
      </li>

      <li class="nav-item">
        <%= link_to 'Contact us', pages_contact_path, class: 'nav-link' %>
      </li>
      

    </ul>

  </div>
</nav>

app/views/shared/_navbaradmin.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">
    <%= image_tag 'Logo-01-01.png' %>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="<%= admin_path %>">Dashboard <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <%= link_to 'Projects', pages_projects_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Add Project', new_project_path, class: 'nav-link btn btn-secondary' %>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <%= link_to "Change your password", edit_user_path %>
      </li>
    </ul>

  </div>
</nav>

app/views/shared/_projectstitle.html.erb
	<div class="">
		<h3 class="subtitle">PROJECTS</h3>
 		<p class="slogan">Making Investments Simple <i class="fas fa-handshake"></i></p>
 		
	</div>

app/views/shared/_widgetprojects.html.erb
	<div class="widget">
        <h5 class="widget-title">PROJECTS</h5>
        <ul class="widget-projects">
          <% @widget.each do |project| %>
          <li>
            <%= link_to project.name, project_path(project), data: { turbolinks: false }, class: '' %>
          </li>

          <% end %>
        </ul>
    </div>