config/routes.rb
Rails.application.routes.draw do
  # devise_for :users

  devise_for :users, controllers: { registrations: "registrations", passwords: "passwords"}

  resource :user, only: [:edit] do
    collection do
      patch 'update_password'
    end
  end
  resources :projects do
    resources :photos, only: [:create, :destroy]
  end

  get 'admin',to: 'admin#index'

  get 'pages/index'

  get 'pages/about'

  get 'pages/projects'

  get 'pages/numbers'

  get 'pages/contact'

  root 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
  mount_uploader :logo, ImageUploader
  has_many :photos
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  layout 'adminlayout'
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: :show
  before_action :set_widget
  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @projects = Project.all
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)
    if @project.save
      redirect_to edit_project_path(@project)
    else
      redirect_to edit_project_path(@project), notice: 'error'
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    if @project.update(project_params)
      redirect_to edit_project_path(@project)
    else
      redirect_to edit_project_path(@project), notice: 'error'
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    redirect_to admin_path
  end

  def make_sold_out
    @project = Project.find(params[:id])
    if @project.sold_out
      @project.sold_out = false
    else
      @project.sold_out = true
    end
    if @project.save
      redirect_to edit_project_path(@project)
    end
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end


    def set_widget
      @widget = Project.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description, :logo)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_with(model: project, local: true) do |form| %>
  <% if project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :project_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :project_description, size: "60x20" %>
  </div>
  <h4 class="text-light">AQUI SE AGREGA EL LOGO</h4>
  <%= form.file_field :logo %>

  <div class="actions">
    <%= form.submit %>
  </div>


<% end %>

app/views/projects/edit.html.erb
<div class="container-fluid p-5 skin">
  <div class="row">
    <h1>Editing Project</h1>

<%= render 'form', project: @project %>


</p>
<p>images of the project</p>
<h3> LOGO</h3>
<% if @project.logo.present? %>
  <%= image_tag @project.logo %>
<% end %>


<div class="row">
  <div class="col-md-12">
    <% if @project.sold_out %>
      <h4>the project is sold out</h4> <br>
    <% else %>
      <h4>the project is not sold out</h4> <br>
    <% end %>
  </div>
  <div class="row">
    <div class="col-md-12">
      <%= form_with(model: [@project, Photo.new], local: true) do |f| %>
        <%= f.file_field :image %>
        <%= f.submit :'add image' %>
      <% end %>
    </div>
  </div>
</div>




<div class="container">
  <div class="row">
    <% @project.photos.each do |photo| %>
      <div class="col-md-3">
        <%= image_tag photo.image, class: 'img-thumbnail', width: '250px' %>
        <%= link_to 'x', project_photo_path(@project,photo), method: :delete, class: 'btn btn-danger btn-sm' %>
      </div>
    <% end %>
  </div>
</div>


<%= link_to 'Show', @project %> |
<%= link_to 'Back', admin_path %>
  </div>
</div>

app/views/projects/index.html.erb
<div class="container-fluid p-5 skin">
  <div class="row">
    <p id="notice"><%= notice %></p>

<h1>Projects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.description %></td>
        <td><%= link_to 'Show', project,class: 'btn' %></td>
        <td><%= link_to 'Edit', edit_project_path(project),class: 'btn' %></td>
        <td><%= link_to 'Destroy', project,class: 'btn', method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

  </div>
</div>

app/views/projects/new.html.erb
<div class="container-fluid p-3 skin">
	<div class="row">
		<h1>New Project</h1>

<%= render 'form', project: @project %>

<%= link_to 'Back', projects_path %>
	</div>
</div>

app/views/projects/show.html.erb
<%= render 'shared/navbar' %>
<div class="container show-body">
  <div class="row">

    <div class="col-md-3">
      <figure class="figure text-right">
          <%= image_tag @project.logo, class: 'figure-img img-fluid', style: 'width: 10rem;' %>
      </figure>
      <%= render 'shared/widgetprojects' %>
      
      
      
    </div>

    <div class="col-md-7 show-content" >
      
     
        
      
      <p class="title-h d-inline-block">

        <%= @project.name %>
      </p>
      

      <!-- GALERIA DE PRODUCTOS -->
      <div class="sp-loading"><%= image_tag 'sp-loading.gif' %><br>Cargando imagenes</div>
      <div class="sp-wrap">
         <% if @project.sold_out %>
          <div class="show-ribbon-box d-flex align-items-center">
            <div class="sold-out-show ">
             <p>
               SOLD OUT
             </p>
                SOLD OUT
              
              
            </div>
            
          </div>
       
        <% end %>
        <% @project.photos.each do |photo| %>

          <a href="<%= photo.image %>"><%= image_tag photo.image %></a>
        <% end %>
      </div>
      <!-- FIN GALERIA DE PRODUCTOS -->

      <p class="content">

        <%= @project.description %>
      </p>



    </div>

    <div class="col-md-2">
      
    </div>

    


  </div>


</div>

<%= render 'shared/footer' %>

	<script type="text/javascript">

    $(document).on('turbolinks:load', function() {
      $(window).load( function() {
          $('.sp-wrap').smoothproducts();
      });
    });
</script>